spring:
  application:
    name: bpms
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://223.247.141.69:3306/webuy_camunda?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true&nullCatalogMeansCurrent=true
    username: user01
    password: ak402507979
    hikari:
      max-lifetime: 30000


camunda:
  bpm:
    history-level: audit
    metrics:
      enabled: false
      db-reporter-activate: false
    job-execution:
      enabled: false




rocket-mq:
  name-server: 122.51.171.126:9876
  producer:
    group: PG_BPMS_TASK_CALLBACK

bpms:
  mq:
    task:
      callback:
        topic: BPMS_TASK_COMPLETE